### ISSUE TITLE
Search and Results table not sorting on Sample name

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#40] opened 2017-06-05 13:56 UTC
QA2
Lexogen
Admin

Clicking `Sample Name` triggers the spinny wheel but no change in sorting in the table
![screen shot 2017-06-05 at 8 55 01 am](https://cloud.githubusercontent.com/assets/1234176/26786615/d4dcb67a-49cc-11e7-972f-33ea3268aa44.jpg)
![screen shot 2017-06-05 at 8 54 52 am](https://cloud.githubusercontent.com/assets/1234176/26786614/d4d97b4a-49cc-11e7-9ccc-a6eda6d3f400.jpg)

**Comment by hadalin** [comment] 2017-06-06 07:12
Hm

This are the two requests

Ordering by name - ascending:

https://qa2.genialis.com/api/_modules/search/sample?offset=0&limit=20&ordering=name&fields=id%2Cslug%2Cname%2Ccreated%2Cdescriptor%2Cdata__id%2Cdata__name%2Cdata__created%2Cdata__modified%2Cdata__process_name%2Cdata__process_progress%2Cdata__status%2Cdata__process_type%2Cdata__input%2Cdata__output&tags=community%3Alexogen&hydrate_data=1

Ordering by name - descending:

https://qa2.genialis.com/api/_modules/search/sample?offset=0&limit=20&ordering=-name&fields=id%2Cslug%2Cname%2Ccreated%2Cdescriptor%2Cdata__id%2Cdata__name%2Cdata__created%2Cdata__modified%2Cdata__process_name%2Cdata__process_progress%2Cdata__status%2Cdata__process_type%2Cdata__input%2Cdata__output&tags=community%3Alexogen&hydrate_data=1

Both responses return the same ordering. Works on local machine.

@dblenkus, @kostko?

**Comment by kostko** [comment] 2017-06-06 09:09
Could be an issue with the combined viewset, I'll look into it.

**Comment by kostko** [comment] 2017-06-06 09:14
Confirmed, the issue is with the combined viewset, the sort order is not respected. You mentioned that it works on your local machine, but it really shouldn't work (unless you forgot the `tags` filter in which case the ordering was done by the database instead of ES).

**Comment by hadalin** [comment] 2017-06-06 09:31
>unless you forgot the tags filter

That's it, no tags filter.

**Comment by kostko** [comment] 2017-06-06 09:37
Should be fixed by genialis/resolwe#296, please test.

**Closed** 2017-06-06 12:30 UTC
Labels: bug
