### ISSUE TITLE
Inconsistent user management behavior

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#11] opened 2017-04-18 18:28 UTC
Server: app.genialis.com
Community: rna-seq
User: rna-seq-demo
Tester: @nejko 

User can log in even if the account has not been activated. After login, there is inconsistent behavior (cannot run particular processes).

Reproduce by: 
- creating a new regular user account and attempting to login without actually confirming account via email
- check ability to run an analysis.

**Comment by kostko** [comment] 2017-04-18 18:44
> creating a new regular user account and attempting to login without actually confirming account via email

Hm, I can't reproduce this. I've created an account "kostko" and I can't login using it.

**Comment by kostko** [comment] 2017-04-18 18:49
The account you mentioned (`rna-seq-demo`) seems to be active and was created 14 days ago. Perhaps someone activated it? Are there multiple recipients for the `demo@genialis.com` e-mail address?

You are correct that the account has not been assigned any permissions, but this might be because 14 days ago there were no default groups configured (not sure if this is the case, I can try to check the audit log).

**Comment by kostko** [comment] 2017-04-18 19:11
I've checked the audit logs and the group associations were created on:
```
Added "DefaultGroup object". 2017-04-07 13:14:13.930190+00:00
Added "DefaultGroup object". 2017-03-27 11:56:20.465583+00:00
```

It also looks like there is a possibility that this account (`rna-seq-demo`) was either created or activated manually (via the admin) and not via the standard registration procedure.

Someone should try to reproduce this with another clean account. Otherwise this bug report may be invalid.

**Comment by dblenkus** [comment] 2017-04-18 20:13
I am almost sure that `rna-seq-demo` user was created via admin.

**Comment by rafecooks** [comment] 2017-04-18 20:29
Indeed, I attempted to recreate with user: bugsbunny pwd: bugsbunny

It seems whatever issue Nejc encountered was fixed in the course of things...

**Comment by nejko** [comment] 2017-04-18 20:52
Can we see how Rna-Seq-demo was created? I mean, even if it was created as an admin, I guess there should be no way the user can log in if the user is not marked as active? So this bug is still there? Can somebody try to reproduce this way?

**Comment by rafecooks** [comment] 2017-04-18 21:24
Nejc, can you very clearly articulate the step-by-step actions you took? Just today I created a new account and was denied sign-in access because I never activated the account. Kostko did too. So maybe we are misunderstanding the sequence of events that led you to report the bug.

**Comment by dblenkus** [comment] 2017-04-19 01:01
Why do you think that `rna-seq-demo` is not active? It is marker as active in Django admin.

**Comment by nejko** [comment] 2017-04-19 05:45
OK, I'll write what I know.

When I asked for a working demo for VCs, Rafe gave me a link to a Google Drive folder with a document, which contained short instructions how to use the demo. The instructions included the username and password for Rna-Seq-demo.

After initial testing I discovered a series of issues that prevented me from exploring the data I tried to upload myself. Now I know that one of the issues was, that I was only just putting two samples in the sample basket. However, things still wouldn't work for Rna-Seq-demo user, i.e. the graphs wouldn't show, etc. And then at some point somebody discovered "but Rna-Seq-demo user is not marked active!". Not sure who that was.

So the key question is: Can somebody create a new user just the way Rna-Seq-demo user was created (who was it)? If yes, please create another the same way and then try to log in with it and upload new data and play with it. If everything works, let me know and I'd be happy to play with it a bit more and try to break it.

**Comment by dblenkus** [comment] 2017-04-19 06:00
I think that you've confused `rna-seq-demo` user with `vc-<something>` user.

`rna-seq-demo` was created by @JenkoB (and I helped to set it up) just day before @rafecooks had RNA-Seq demo. So there is no option that it wouldn't be activated or wouldn't work (there may be some bugs, but non specifically related to that user).

You are probably talking about `vc-<something>` user that you've created a week after `rna-seq-demo` user. The problem with it was that @lukaw3d couldn't assigned any permissions to it, because it wasn't activated at the time. But this is also already fixed (activated).

**Comment by kostko** [comment] 2017-04-19 06:03
The thing is that if you manually edit users via the admin, you have to manually activate the account and you have to manually take care of permissions/groups. Automatic permission assignment is only for users activated via the registration procedure not for users that are manually created via the admin. AFAIK, this is the correct functionality.

**Comment by dblenkus** [comment] 2017-04-19 06:04
@nejc I think that you are talking about activated user that is not assigned to any group and thus has no permissions to do anything. This is not the most useful state (and can be achieved only through Django admin), but is still valid.

**Comment by JenkoB** [comment] 2017-04-19 07:07
I have created rna-seq-demo user the same way as lexogen-demo and the same way I am creating accounts for BCM users. This is through the admin page, where I also assign the group with process permissions and then manually I add data permissions through BD.

**Comment by JenkoB** [comment] 2017-04-19 07:20
For the first time I tried to create a new user with my gmail account on app.genialis.com through registering account and I can not login, so I have reset the password and I can not set a new one, because anything that I remember is considered as Bad password reset token, what requirements do we have for a good password? Can we write them in setting password page?

**Closed** 2017-04-25 09:01 UTC
