### ISSUE TITLE
Input object in sample view can not be clicked

### ISSUE THREAD

**Issue by dblenkus** [genialis/bug-reports#6] opened 2017-04-13 18:50 UTC
Steps to reproduce:

- go to sample view ([click](https://en.wikipedia.org/wiki/List_of_pasta))
- find object with input object (i.e. `BBDuk (single-end)` -> `Reads`)
- click `view` next to input object

![screen shot 2017-04-13 at 13 48 43](https://cloud.githubusercontent.com/assets/5970282/25019408/11930c96-2050-11e7-9a56-e0bcd8c90fe3.png)

![screen shot 2017-04-13 at 13 50 07](https://cloud.githubusercontent.com/assets/5970282/25019438/286f1e8c-2050-11e7-8fe0-c4882d2dfe20.png)

**Comment by mstajdohar** [comment] 2017-04-25 09:05
Related to https://github.com/genialis/genialis-apps/issues/486. @hadalin Consider merging the two bug reports.

**Comment by hadalin** [comment] 2017-05-03 09:39
> go to sample view (click)

The link points to https://en.wikipedia.org/wiki/List_of_pasta

**Comment by hadalin** [comment] 2017-05-03 12:35
Closing because duplicate of https://github.com/genialis/genialis-apps/issues/486

**Closed by hadalin** 2017-05-03 12:35 UTC
Labels: bug
